### ISSUE TITLE
Code review - Colin | Marcin | Nadia

### ISSUE THREAD

**Issue by MarsGotBars** [ambersr/fix-the-flow-interactive-website#18]
# Issues

### CamelCasing
je [currentslide](https://github.com/ambersr/fix-the-flow-interactive-website/blob/c24feacda8a3cc1e731f83312584750c95fdc13a/scripts/script.js#L5) variabele is niet ge-camelcased, verander deze naar currentSlide voor consistentie en leesbaarheid.

### Probeer css en js apart te houden
Probeer een andere manier te bedenken waarop je de slides kan [bewegen](https://github.com/ambersr/fix-the-flow-interactive-website/blob/c24feacda8a3cc1e731f83312584750c95fdc13a/scripts/script.js#L9)

### Dubbele function call
Is [deze](https://github.com/ambersr/fix-the-flow-interactive-website/blob/c24feacda8a3cc1e731f83312584750c95fdc13a/scripts/script.js#L44C1-L49) call niet dubbelop? Volgens mij zou je de eerste function call weg kunnen halen.

### Niet toegepast op website
Waarom heb je dit op een aparte pagina staan? Hoort dit niet bij je project? Zo wel, zet het er dan in.
### Feedback/Feedforward
Werkt goed, ook goed nagedacht over disabled states, wel zou ik persoonlijk _of_ de slides weer terug loopen van 3 naar 1 of de arrow visueel verbergen ipv uit zetten.

**Comment by ambersr** [comment]
## Javascript

- **CamelCasing**

Dit heb ik opgelost!

Commit: 64af8320c776c1d2f0b0f7f055ac872baab1e1fe

- **Styling apart van javascript**

Ik heb de styling element los getrokken uit de Javascript. Ik heb in CSS meerdere classes aangemaakt waarin ik de animatie van de slides heb aangemaakt. Aan de hand van`slidesContainer.classList.remove('slide-0', 'slide-1', 'slide-2');` en ` slidesContainer.classList.add(`slide-${currentSlide}`);` heb ik ervoor gezorgd dat er classes toegevoegd en verwijderd worden van de desbetreffende slide.

Commit: abe7bea7b5041d125b8eb3ea513ffeae6cef76cf

- Overbodige code

Klopt dit was inderdaad overbodig.

Commit: b960bbcaf978f23bf1f23cf39b3d37d43f709f60

**Comment by ambersr** [comment]
## Design

- **Niet toegepast website**

Dit klopt. Ik heb de afgelopen week meer gefocust op javascript en minder in het schrijven van de andere pagina's. Deze zijn nu wel af hier het linkje naar de pagina waar de carousel staat: https://ambersr.github.io/fix-the-flow-interactive-website/partner.html#reviews

- **Feedback/Feedforward**

Dit laat ik voor nu zo. Ik heb dit met koop besproken. Ik heb nog wel labels toegevoegd aan de knoppen.

**Comment by ambersr** [comment]
## Design

- **Niet toegepast website**

Dit klopt. Ik heb de afgelopen week meer gefocust op javascript en minder in het schrijven van de andere pagina's. Deze zijn nu wel af hier het linkje naar de pagina waar de carousel staat: https://ambersr.github.io/fix-the-flow-interactive-website/partner.html#reviews

- **Feedback/Feedforward**

Dit laat ik voor nu zo. Ik heb dit met koop besproken. Ik heb nog wel labels toegevoegd aan de knoppen.
