### ISSUE TITLE
button active state 

### ISSUE THREAD

**Issue by KoopReynders** [ambersr/fix-the-flow-interactive-website#19]
Het zou mooi zijn als de buttons ook een active state krijgen, dan ziet een gebruiker dat die de button klikt. (feedback)
En een label toevoegen met feedforward.

**Comment by ambersr** [comment]
Ik heb nu een active state toegevoegd. Hierop heb ik de scale iets aangepast waardoor het een wobble effect krijgt wanneer je op de knop klikt. 

Commit:https://github.com/ambersr/fix-the-flow-interactive-website/commit/49ce7216fe50098024fd511e04c03913aba42ec0

Daarnaast heb ik ook een label toegevoegd bij de knoppen. Het is nog wel een beetje lastig om dit goed naar voren te laten komen. Ik heb nu de label onder het pijltje geplaatst. Voor nu heb ik het op deze manier opgelost (Zie afbeelding). 

<img width="681" alt="image" src="https://github.com/user-attachments/assets/05ed78c9-64a1-4591-8e5a-5ad8ddfc48f6">

**Comment by KoopReynders** [comment]
Ziet er goed uit Amber. Netjes hoor.
